[package]
name = "aoc2020"
version = "0.1.0"
authors = ["Fenhl <fenhl@fenhl.net>"]
edition = "2018"

[dependencies]
aoc-runner = "0.3"
aoc-runner-derive = "0.3"
hashbag = "0.1"
itertools = "0.9"
lazy_static = "1"
regex = "1"
